/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ftof_jni_HttpUtils */

#ifndef _Included_com_ftof_jni_HttpUtils
#define _Included_com_ftof_jni_HttpUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ftof_jni_HttpUtils
 * Method:    getAppData
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ftof_jni_HttpUtils_getAppData
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_ftof_jni_HttpUtils
 * Method:    postAppData
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ftof_jni_HttpUtils_postAppData
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_ftof_jni_HttpUtils
 * Method:    postLog
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ftof_jni_HttpUtils_postLog
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_ftof_jni_HttpUtils
 * Method:    postActive
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ftof_jni_HttpUtils_postActive
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
